ALTER TABLE season_stats
    ADD COLUMN IF NOT EXISTS ops_plus INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS wrc_plus INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS era_plus INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fip DECIMAL(5,2) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS war DECIMAL(5,1) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS war_per_dollar DECIMAL(8,4) DEFAULT 0;

ALTER TABLE season_stats
    DROP COLUMN IF EXISTS age,
    DROP COLUMN IF EXISTS games_started,
    DROP COLUMN IF EXISTS plate_appearances,
    DROP COLUMN IF EXISTS doubles,
    DROP COLUMN IF EXISTS triples,
    DROP COLUMN IF EXISTS runs,
    DROP COLUMN IF EXISTS walks,
    DROP COLUMN IF EXISTS babip,
    DROP COLUMN IF EXISTS hits_allowed,
    DROP COLUMN IF EXISTS walks_allowed,
    DROP COLUMN IF EXISTS home_runs_allowed,
    DROP COLUMN IF EXISTS strikeouts_per_9,
    DROP COLUMN IF EXISTS walks_per_9,
    DROP COLUMN IF EXISTS hits_per_9,
    DROP COLUMN IF EXISTS home_runs_per_9,
    DROP COLUMN IF EXISTS strikeout_walk_ratio,
    DROP COLUMN IF EXISTS strike_percentage,
    DROP COLUMN IF EXISTS expected_batting_avg,
    DROP COLUMN IF EXISTS expected_slugging,
    DROP COLUMN IF EXISTS expected_woba,
    DROP COLUMN IF EXISTS expected_era,
    DROP COLUMN IF EXISTS barrel_pct,
    DROP COLUMN IF EXISTS hard_hit_pct,
    DROP COLUMN IF EXISTS avg_exit_velocity,
    DROP COLUMN IF EXISTS avg_launch_angle,
    DROP COLUMN IF EXISTS sweet_spot_pct;
